-- MySQL Script generated by MySQL Workbench
-- Tue May 28 21:04:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`board` ;

CREATE TABLE IF NOT EXISTS `mydb`.`board` (
  `board_seq` INT NOT NULL AUTO_INCREMENT,
  `category_seq` INT NOT NULL,
  `board_title` VARCHAR(500) NULL,
  `board_content` VARCHAR(2000) NULL,
  `board_div_cd` VARCHAR(2) NULL,
  `reg_id` VARCHAR(255) NULL,
  `reg_date` VARCHAR(45) NULL,
  `reg_ip` VARCHAR(45) NULL,
  `user_seq` INT NOT NULL,
  PRIMARY KEY (`board_seq`),
  CONSTRAINT `fk_board_category1`
    FOREIGN KEY (`category_seq`)
    REFERENCES `mydb`.`category` (`category_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_board_user1`
    FOREIGN KEY (`user_seq`)
    REFERENCES `mydb`.`user` (`user_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_board_category1_idx` ON `mydb`.`board` (`category_seq` ASC);

CREATE INDEX `fk_board_user1_idx` ON `mydb`.`board` (`user_seq` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`board_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`board_comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`board_comments` (
  `comment_seq` INT NOT NULL AUTO_INCREMENT,
  `comment_text` VARCHAR(1000) NOT NULL,
  `reg_id` VARCHAR(255) NOT NULL,
  `reg_ip` VARCHAR(45) NOT NULL,
  `reg_date` DATE NOT NULL,
  `board_seq` INT NOT NULL,
  `user_seq` INT NOT NULL,
  PRIMARY KEY (`comment_seq`),
  CONSTRAINT `fk_board_comments_board1`
    FOREIGN KEY (`board_seq` , `user_seq`)
    REFERENCES `mydb`.`board` (`board_seq` , `user_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_board_comments_board1_idx` ON `mydb`.`board_comments` (`board_seq` ASC, `user_seq` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`board_likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`board_likes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`board_likes` (
  `like_seq` INT NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `reg_id` VARCHAR(255) NOT NULL COMMENT '유저 아이디',
  `reg_date` VARCHAR(45) NOT NULL COMMENT '등록일',
  `board_seq` INT NOT NULL,
  `user_seq` INT NOT NULL,
  PRIMARY KEY (`like_seq`),
  CONSTRAINT `fk_board_likes_board1`
    FOREIGN KEY (`board_seq` , `user_seq`)
    REFERENCES `mydb`.`board` (`board_seq` , `user_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_board_likes_board1_idx` ON `mydb`.`board_likes` (`board_seq` ASC, `user_seq` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_seq` VARCHAR(255) NOT NULL COMMENT '카테고리 번호',
  `category_name` VARCHAR(255) CHARACTER SET 'DEFAULT' NULL COMMENT '카테고리명',
  `category_lvl` INT NOT NULL DEFAULT 0 COMMENT '카테고리 레벨',
  `parent_category_seq` VARCHAR(255) NOT NULL,
  `reg_date` DATE NOT NULL,
  `reg_id` VARCHAR(255) NOT NULL,
  `reg_ip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_seq`),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_category_seq`)
    REFERENCES `mydb`.`category` (`category_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_category_category1_idx` ON `mydb`.`category` (`parent_category_seq` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`login_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`login_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`login_history` (
  `seq` INT NOT NULL AUTO_INCREMENT COMMENT '로그인 시퀀스',
  `login_ip` VARCHAR(45) NOT NULL COMMENT '로그인 아이디\n',
  `login_date` DATE NOT NULL COMMENT '로그인 날짜',
  `login_status` VARCHAR(3) NOT NULL COMMENT '로그인 결과',
  `user_num` INT NOT NULL,
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_login_history_user`
    FOREIGN KEY (`user_num`)
    REFERENCES `mydb`.`user` (`user_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_login_history_user_idx` ON `mydb`.`login_history` (`user_num` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`photo_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`photo_comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`photo_comments` (
  `comment_seq` INT NOT NULL AUTO_INCREMENT,
  `comment_text` VARCHAR(1000) NOT NULL,
  `reg_id` VARCHAR(255) NOT NULL,
  `reg_ip` VARCHAR(45) NOT NULL,
  `reg_date` DATE NOT NULL,
  `photo_seq` INT NOT NULL,
  `user_seq` INT NOT NULL,
  PRIMARY KEY (`comment_seq`),
  CONSTRAINT `fk_comments_photos1`
    FOREIGN KEY (`photo_seq` , `user_seq`)
    REFERENCES `mydb`.`photos` (`photo_seq` , `user_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comments_photos1_idx` ON `mydb`.`photo_comments` (`photo_seq` ASC, `user_seq` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`photo_likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`photo_likes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`photo_likes` (
  `like_seq` INT NOT NULL COMMENT '시퀀스',
  `reg_id` VARCHAR(255) NOT NULL COMMENT '유저 아이디',
  `reg_date` VARCHAR(45) NOT NULL COMMENT '등록일',
  `photo_seq` INT NOT NULL,
  `user_seq` INT NOT NULL,
  PRIMARY KEY (`like_seq`),
  CONSTRAINT `fk_like_photos1`
    FOREIGN KEY (`photo_seq` , `user_seq`)
    REFERENCES `mydb`.`photos` (`photo_seq` , `photo_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_like_photos1_idx` ON `mydb`.`photo_likes` (`photo_seq` ASC, `user_seq` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`photos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`photos` (
  `photo_seq` INT NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `category_seq` INT NOT NULL COMMENT '카테고리 번호\n',
  `user_seq` INT NOT NULL,
  `photo_url` VARCHAR(500) NULL COMMENT '사진 url',
  `photo_name` VARCHAR(500) NULL COMMENT '사진 찍은 위치',
  `photo_path` VARCHAR(500) NULL COMMENT '사진 실제 경로',
  `reg_id` VARCHAR(255) NOT NULL COMMENT '등록자',
  `reg_date` DATE NOT NULL COMMENT '등록자 ip',
  `reg_ip` VARCHAR(45) NOT NULL COMMENT '등록자 ip',
  PRIMARY KEY (`photo_seq`),
  CONSTRAINT `fk_photos_category1`
    FOREIGN KEY (`category_seq`)
    REFERENCES `mydb`.`category` (`category_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photos_user1`
    FOREIGN KEY (`user_seq`)
    REFERENCES `mydb`.`user` (`user_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_photos_category1_idx` ON `mydb`.`photos` (`category_seq` ASC);

CREATE INDEX `fk_photos_user1_idx` ON `mydb`.`photos` (`user_seq` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_seq` INT NOT NULL AUTO_INCREMENT COMMENT '유저 시퀀스',
  `user_name` VARCHAR(50) NOT NULL COMMENT '유저 이름',
  `user_id` VARCHAR(255) NOT NULL COMMENT '유저 아이디',
  `user_password` VARCHAR(255) NOT NULL COMMENT '유저 비밀번호',
  `gender` VARCHAR(2) NULL COMMENT '이메일',
  `address` VARCHAR(255) NULL COMMENT '이메일',
  `phone_num` VARCHAR(255) NULL COMMENT '이메일',
  `email` VARCHAR(255) NULL COMMENT '이메일',
  `user_status` VARCHAR(3) COLLATE 'DEFAULT' NOT NULL DEFAULT '00' COMMENT '회원 상태 값\n',
  `create_time` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '가입일',
  PRIMARY KEY (`user_seq`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
